/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SongscrawlerRecord extends org.jooq.impl.TableRecordImpl<tech.codingclub.helix.tables.records.SongscrawlerRecord> implements org.jooq.Record1<java.lang.String> {

	private static final long serialVersionUID = -369822040;

	/**
	 * Setter for <code>public.songscrawler.parent_link</code>.
	 */
	public void setParentLink(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.songscrawler.parent_link</code>.
	 */
	public java.lang.String getParentLink() {
		return (java.lang.String) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> fieldsRow() {
		return (org.jooq.Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> valuesRow() {
		return (org.jooq.Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return tech.codingclub.helix.tables.Songscrawler.SONGSCRAWLER.PARENT_LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getParentLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongscrawlerRecord value1(java.lang.String value) {
		setParentLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongscrawlerRecord values(java.lang.String value1) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SongscrawlerRecord
	 */
	public SongscrawlerRecord() {
		super(tech.codingclub.helix.tables.Songscrawler.SONGSCRAWLER);
	}

	/**
	 * Create a detached, initialised SongscrawlerRecord
	 */
	public SongscrawlerRecord(java.lang.String parentLink) {
		super(tech.codingclub.helix.tables.Songscrawler.SONGSCRAWLER);

		setValue(0, parentLink);
	}
}
