/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Songscrawler extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.SongscrawlerRecord> {

	private static final long serialVersionUID = 1633968848;

	/**
	 * The singleton instance of <code>public.songscrawler</code>
	 */
	public static final tech.codingclub.helix.tables.Songscrawler SONGSCRAWLER = new tech.codingclub.helix.tables.Songscrawler();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.SongscrawlerRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.SongscrawlerRecord.class;
	}

	/**
	 * The column <code>public.songscrawler.parent_link</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongscrawlerRecord, java.lang.String> PARENT_LINK = createField("parent_link", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * Create a <code>public.songscrawler</code> table reference
	 */
	public Songscrawler() {
		this("songscrawler", null);
	}

	/**
	 * Create an aliased <code>public.songscrawler</code> table reference
	 */
	public Songscrawler(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Songscrawler.SONGSCRAWLER);
	}

	private Songscrawler(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.SongscrawlerRecord> aliased) {
		this(alias, aliased, null);
	}

	private Songscrawler(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.SongscrawlerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Songscrawler as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Songscrawler(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Songscrawler rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Songscrawler(name, null);
	}
}
